### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by larrasket** [aezarebski/aezarebski.github.io#1]
Hi, Alex. I really love how your site looks like. Could you please provide some information about which static site generator do you use, or how do you build it? Thanks in advance.

**Comment by aezarebski** [comment]
Hi @salehmu,

I'm glad you enjoyed the site :)

Most of the pages are plain old org-mode which has been exported to HTML and then styled with a little bit of CSS ([LINK](https://github.com/aezarebski/aezarebski.github.io/blob/master/css/stylesheet.css)), the configuration for this is described here ([LINK](https://aezarebski.github.io/misc/nicemacs/nicemacs.html#orge095879))  but its not super clear, you might be better off just looking at the org-mode website for details about how to do this.

The homepage I wrote by hand because that seemed to be the easiest way to get the layout I wanted. Nothing fancy.

Best of Luck,
Alex
